# Generated by Django 5.2.4 on 2025-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('idCar', models.AutoField(primary_key=True, serialize=False)),
                ('modelCar', models.CharField(max_length=200)),
                ('brandCar', models.CharField(max_length=200)),
                ('factoryYear', models.IntegerField(blank=True, null=True)),
                ('modelYear', models.IntegerField(blank=True, null=True)),
                ('valueCar', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
