# Generated by Django 5.2.4 on 2025-07-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('idBrand', models.AutoField(primary_key=True, serialize=False)),
                ('nameBrand', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brandCar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carBrand', to='cars.brand'),
        ),
    ]
