# Generated by Django 5.2.4 on 2025-08-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bioCar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
