# Generated by Django 5.2.4 on 2025-09-05 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_biocar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carOwner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ownerCar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
