# Generated by Django 5.2.4 on 2025-09-05 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_carowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carStatus',
            field=models.CharField(choices=[('novo', 'Novo'), ('seminovo', 'Seminovo'), ('usado', 'Usado')], default='novo', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='carOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerCar', to=settings.AUTH_USER_MODEL),
        ),
    ]
